import {useEffect,useState} from 'react';
import {learningService,type LearningService} from './services/learning';
import type {Exercise,Lesson,Progress,RunResult,TheoryPart} from './types';
import './styles.css';
const difficulty={basic:'Базовая',intermediate:'Средняя',advanced:'Повышенная'};
const labels:Record<RunResult['status'],string>={success:'Выполнено',runtime_error:'Ошибка выполнения',import_error:'Недоступный модуль',syntax_error:'Синтаксическая ошибка',timeout:'Превышено время выполнения',output_limit:'Слишком много вывода',runner_error:'Ошибка приложения'};
function Theory({parts}:{parts:TheoryPart[]}){return <article className="reading"><h2>Теория</h2>{parts.map((p,i)=>p.type==='heading'?<h3 key={i}>{p.text}</h3>:p.type==='paragraph'?<p key={i}>{p.text}</p>:<pre key={i}><code>{p.code}</code></pre>)}</article>}
function CodeEditor({value,onChange}:{value:string;onChange:(v:string)=>void}){return <textarea className="code-editor" aria-label="Редактор Python-кода" spellCheck={false} value={value} onChange={e=>onChange(e.target.value)} onKeyDown={e=>{if(e.key==='Tab'){e.preventDefault();const el=e.currentTarget,start=el.selectionStart,end=el.selectionEnd;onChange(value.slice(0,start)+'    '+value.slice(end));requestAnimationFrame(()=>el.selectionStart=el.selectionEnd=start+4)}}}/>}
function ExerciseView({lessonId,exercise,code,setCode,service}:{lessonId:string;exercise:Exercise;code:string;setCode:(v:string)=>void;service:LearningService}){const[running,setRunning]=useState(false),[output,setOutput]=useState<RunResult|null>(null),[failed,setFailed]=useState(false);async function run(){if(running)return;setRunning(true);setFailed(false);try{setOutput(await service.runExercise({protocol_version:1,lesson_id:lessonId,exercise_id:exercise.id,code}))}catch{setOutput(null);setFailed(true)}finally{setRunning(false)}}return <article className="reading"><span className={`badge ${exercise.difficulty}`}>{difficulty[exercise.difficulty]}</span><h2>{exercise.title}</h2><p>{exercise.statement}</p><h3>Код</h3><CodeEditor value={code} onChange={setCode}/>{exercise.assets.map(a=><p className="asset" key={a.id}>Файл: <code>{a.filename}</code> — {a.description}</p>)}<button className="run" disabled={running} onClick={run}>{running?'Выполняется…':'Запустить'}</button><section className="output" aria-live="polite"><h3>Результат выполнения</h3>{failed&&<p className="error">Ошибка приложения. Среда выполнения недоступна.</p>}{output&&<><strong>{labels[output.status]}</strong>{output.stdout&&<pre><code>{output.stdout}</code></pre>}{output.stderr&&<pre className="stderr"><code>{output.stderr}</code></pre>}{output.truncated&&<p>Вывод был ограничен.</p>}</>}</section><h3>Подсказки</h3><ul>{exercise.hints.map(h=><li key={h}>{h}</li>)}</ul></article>}
export function LessonPage({lessonId,service=learningService}:{lessonId:string;service?:LearningService}){const[lesson,setLesson]=useState<Lesson|null>(null),[progress,setProgress]=useState<Progress|null>(null),[selected,setSelected]=useState('theory'),[error,setError]=useState(''),[drafts,setDrafts]=useState<Record<string,string>>({});useEffect(()=>{let live=true;setError('');Promise.all([service.loadLesson(lessonId),service.loadLessonProgress(lessonId)]).then(([l,p])=>{if(live){if(!l.blocks?.[0]||typeof p.percent!=='number')throw new Error('INVALID_RESPONSE');setLesson(l);setProgress(p);setDrafts(d=>{const next={...d};for(const b of l.blocks)for(const e of b.exercises)next[`${e.id}@${l.content_version}`]??=e.starter_code;return next})}}).catch(e=>{if(live)setError(e instanceof Error?e.message:'APP_ERROR')});return()=>{live=false}},[lessonId,service]);if(error)return <main className="state"><h1>{error.includes('NOT_FOUND')?'Урок не найден':'Не удалось загрузить урок'}</h1></main>;if(!lesson||!progress)return <main className="state" aria-live="polite">Загружаем урок и прогресс…</main>;const block=lesson.blocks[0],current=block.exercises.find(e=>e.id===selected),key=current?`${current.id}@${lesson.content_version}`:'';return <main className="page"><header className="hero"><div><p className="eyebrow">{lesson.age_group}</p><h1>{lesson.title}</h1><p className="block-title">{block.title}</p></div><section className="progress-card"><strong>Прогресс урока</strong><div className="progress-copy"><span>{progress.completed} / {progress.total} заданий</span><span>{progress.percent}%</span></div><progress aria-label="Прогресс урока" max={100} value={progress.percent}/></section></header><div className="layout"><nav aria-label="Разделы урока"><button className={selected==='theory'?'active':''} onClick={()=>setSelected('theory')}>Теория</button>{block.exercises.map((e,i)=><button key={e.id} className={selected===e.id?'active':''} onClick={()=>setSelected(e.id)}>Задача {i+1}</button>)}</nav>{current?<ExerciseView lessonId={lesson.id} exercise={current} code={drafts[key]??current.starter_code} setCode={v=>setDrafts(d=>({...d,[key]:v}))} service={service}/>:<Theory parts={block.theory.parts}/>}</div></main>}
export default function App(){const match=location.pathname.match(/^\/lessons\/([^/]+)$/);return match?<LessonPage lessonId={decodeURIComponent(match[1])}/>:<main className="state"><h1>Откройте урок</h1></main>}
